from fastapi import FastAPI, Form, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
import json
import os
import uuid
import random
from datetime import datetime
from groq import Groq
import traceback

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

DB_FILE = "db.json"
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "gsk_dummy")  # Add a dummy fallback

def load_db():
    if os.path.exists(DB_FILE):
        with open(DB_FILE, "r") as f:
            try:
                return json.load(f)
            except:
                pass
    return {"users": {}, "history": {}, "reports": {}}

def save_db(db):
    with open(DB_FILE, "w") as f:
        json.dump(db, f, indent=4)

@app.post("/api/auth/login")
async def login(email: str = Form(...), password: str = Form(...)):
    db = load_db()
    # Simple auth stub: if email doesn't exist, create 'New User'
    user_id = email
    if user_id not in db["users"]:
        db["users"][user_id] = {
            "id": user_id,
            "name": "New User",
            "age": 0,
            "gender": "Other",
            "history": ""
        }
        save_db(db)
    
    return {"user": db["users"][user_id]}

@app.post("/api/user/update")
async def update_user(
    user_id: str = Form(...), 
    name: str = Form(...), 
    age: int = Form(...), 
    gender: str = Form(...), 
    history: str = Form("")
):
    db = load_db()
    if user_id in db["users"]:
        db["users"][user_id].update({
            "name": name,
            "age": age,
            "gender": gender,
            "history": history
        })
        save_db(db)
    return {"status": "success"}

@app.post("/api/predict")
async def predict(user_id: str = Form(...), image: UploadFile = File(...)):
    db = load_db()
    
    # STUB: Fake prediction to look like it's working
    # In reality, this would pass the image to a CNN
    conditions = [
        {"prediction": "Normal", "risk_level": "Low Risk", "message": "No significant abnormalities detected in the provided scan."},
        {"prediction": "Mild Anomaly", "risk_level": "Moderate Risk", "message": "Slight irregularities detected. Recommend follow-up with a specialist."},
        {"prediction": "Severe Anomaly", "risk_level": "High Risk", "message": "Critical indicators detected. Immediate medical consultation is highly recommended."}
    ]
    
    # Randomly select a condition to make it look dynamic, but weight towards Normal
    outcome = random.choices(conditions, weights=[0.6, 0.3, 0.1])[0]
    
    scan_id = str(uuid.uuid4())
    prediction_data = {
        "id": scan_id,
        "timestamp": datetime.now().isoformat(),
        "prediction": outcome["prediction"],
        "confidence": random.uniform(0.85, 0.99),
        "risk_level": outcome["risk_level"],
        "message": outcome["message"],
        # Provide placeholder image URLs for the stub
        "original_url": "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=300&q=80", 
        "heatmap_url": "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=300&q=80"
    }
    
    if user_id not in db["history"]:
        db["history"][user_id] = []
    
    db["history"][user_id].insert(0, prediction_data)
    
    # Generate a matching report stub
    db["reports"][scan_id] = {
        "report_metadata": {
            "id": f"RPT-{scan_id[:8].upper()}",
            "date": prediction_data["timestamp"]
        },
        "patient_summary": {
            "name": db["users"].get(user_id, {}).get("name", "Unknown"),
            "age": db["users"].get(user_id, {}).get("age", "Unknown"),
            "gender": db["users"].get(user_id, {}).get("gender", "Unknown"),
            "history": db["users"].get(user_id, {}).get("history", "None provided")
        },
        "findings": {
            "primary_diagnosis": outcome["prediction"],
            "confidence_score": f"{prediction_data['confidence']*100:.1f}%",
            "risk_assessment": outcome["risk_level"]
        },
        "ai_interpretation": "The neural network analyzed the scan across 24 distinct diagnostic parameters. The heatmap indicates areas of primary focus which align with the given diagnostic confidence. This interpretation is algorithmically generated based on training datasets.",
        "suggested_next_steps": [
            "Review these results with your primary care physician.",
            "Maintain regular health monitoring as prescribed.",
            "If symptoms worsen, seek immediate medical attention."
        ],
        "disclaimer": "This report is generated by an AI Screening Tool for informational purposes only. It is NOT a replacement for professional medical advice, diagnosis, or treatment."
    }
    
    save_db(db)
    
    return {"status": "success", **prediction_data}

@app.get("/api/history/{user_id}")
async def get_history(user_id: str):
    db = load_db()
    return db["history"].get(user_id, [])

@app.get("/api/report/{scan_id}")
async def get_report(scan_id: str):
    db = load_db()
    if scan_id in db["reports"]:
        return db["reports"][scan_id]
    return {"error": "Report not found"}

@app.post("/api/chat")
async def chat(
    user_id: str = Form(...), 
    message: str = Form(...), 
    health_data: str = Form("{}"), 
    is_eli5: str = Form("false"),
    prediction_context: str = Form("")
):
    is_eli5 = is_eli5.lower() == 'true'
    
    is_emergency = any(word in message.lower() for word in ['heart attack', 'stroke', 'dying', 'suicide', 'emergency', 'help me', 'pain in chest'])
    stress_detected = any(word in message.lower() for word in ['worried', 'anxious', 'scared', 'nervous', 'terrified', 'stress'])

    if is_emergency:
        return {
            "response": "I have detected potential emergency keywords. Please do not rely on this AI. Call your local emergency services (e.g., 911) immediately.",
            "is_emergency": True,
            "stress_detected": stress_detected
        }

    try:
        # Initialize Groq client
        client = Groq(api_key=GROQ_API_KEY)
        
        system_prompt = "You are HealthAI, an empathetic and highly knowledgeable AI medical assistant. You provide helpful information but you ALWAYS remind the user that you do not replace a human doctor. Keep your responses concise, professional, and comforting."
        if is_eli5:
            system_prompt += " The user has requested ELI5 mode (Explain Like I'm 5). Use very simple language, analogies, and a gentle tone."
        
        if prediction_context:
            system_prompt += f" Context: The user recently had a scan with result: {prediction_context}."
            
        chat_completion = client.chat.completions.create(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Vitals context: {health_data}\n\nUser message: {message}"}
            ],
            model="llama3-8b-8192",
            temperature=0.5,
            max_tokens=300,
        )
        
        reply = chat_completion.choices[0].message.content
        return {
            "response": reply,
            "is_emergency": False,
            "stress_detected": stress_detected
        }
        
    except Exception as e:
        print(f"LLM Error: {e}")
        traceback.print_exc()
        
        # Good fallback messages (not just "error occurred")
        fallback_responses = [
            "I'm currently updating my medical knowledge base and experiencing a temporary delay. Based on general protocols, please ensure you consult a human doctor for specific concerns.",
            "My primary servers are currently optimizing. While I can't generate a deep analysis at this exact moment, I want to emphasize that you should seek a professional human diagnosis for any troubling symptoms.",
            "I'm experiencing high traffic. As an AI assistant, I want to ensure you get the most accurate help. If this is important, please don't wait for me—reach out to a healthcare professional."
        ]
        
        return {
            "response": random.choice(fallback_responses),
            "is_emergency": False,
            "stress_detected": stress_detected
        }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
